### ISSUE TITLE
HexApi And Lavalink

### ISSUE THREAD

**Issue by ROYAL-HarsH** [1Prototype1/HexBot#10]
Please Help About HexApi And Lavalink
Error = "Invalid response received; this may indicate that Lavalink is not running, or is running on a port different to the one you passed to `add_node`."
Error = "In embed.image.url: Scheme "none" is not supported. Scheme must be one of ('http', 'https')."
Error = "discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'HexApi'"
Please Help.

**Comment by 1Prototype1** [comment]
As mentioned on the first line itself of the README, this repo isn't being maintained any more.
It may contain code which may/may not work. I have kept this repo just for the reference for new bot developers. The bot as whole wont work just some commands may still work though.
The current version of HexBot is private and no longer open sourced.

HexAPI is private API and Lavalink needs to be updated every few days (blame YT) so don't expect it to be working with this super old version.
