### ISSUE TITLE
Music doesn't play clear

### ISSUE THREAD

**Issue by NightZan999** [1Prototype1/HexBot#11]
**Describe the bug**
When I play music, the music comes in blurred and I don't think this works because of the API. The Lavalink API that music is using is bugged. 

**Expected behavior**
I expected music to play!

**Device**
 - **Desktop**
  - OS: Windows
  - Browser Chrome
  
**Discord Version**
 - [e.g.Stable 66086 (ac54a7f)]
 
**Additional context**
How to fix this?

**Comment by 1Prototype1** [comment]
The Lavalink needs to be at latest version to work properly. 
If you are trying to run this whole bot; **it wont work!**
