### ISSUE TITLE
The Lyrics command is broken.

### ISSUE THREAD

**Issue by CharliePlayz** [1Prototype1/HexBot#13]
I keep getting error: An error occurred: Command raised an exception: AttributeError: 'Music' object has no attribute 'kclient'

**Comment by 1Prototype1** [comment]
kclient is an attribute that uses the KSoft API.
It is initialized here and you need to have KSoft token in env
https://github.com/1Prototype1/HexBot/blob/43eabcb52c2ed56c00c20fe7fbd12bb19d550ff8/hexbot.py#L26
Unfortunately, right now the lyrics endpoint is disabled so no use of applying for it

You'll have to work on an alternative ☹
