### ISSUE TITLE
HexApi

### ISSUE THREAD

**Issue by justanothernoob4648** [1Prototype1/HexBot#8]
What is HexApi? Can I use it?

**Comment by 1Prototype1** [comment]
HexAPI is an API used by HexBot to get various content.
It is hosted on my server. 
Right now I haven't planned on releasing it so kept the url hidden.
The server is powerful enough but maybe I'll make it public after adding some auth later on.

**Comment by MystYT-21** [comment]
> HexAPI is an API used by HexBot to get various content.
> It is hosted on my server.
> Right now I haven't planned on releasing it so kept the url hidden.
> The server is powerful enough but maybe I'll make it public after adding some auth later on.

It would be kinda cool to use after u said it's really powerful! Damn

**Comment by ROYAL-HarsH** [comment]
Bot Is Not Responding Any Command And Sending Errors Realeted To HexApi

**Comment by 1Prototype1** [comment]
Closing this since there are no plans yet for making HexAPI public.
HexAPI will be rewritten and made serverless; maybe that time I may think of making some of its endpoints public 😄
